/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddPowerDialog: typeof import('./src/components/AddPowerDialog.vue')['default']
    AddScoreDialog: typeof import('./src/components/AddScoreDialog.vue')['default']
    CommonDialog: typeof import('./src/components/CommonDialog.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TakeOutDialog: typeof import('./src/components/TakeOutDialog.vue')['default']
    TeamModule: typeof import('./src/components/TeamModule.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
  }
}
